### PR TITLE
Added Division

### PR DESCRIPTION
**Pull request by mathiasquintero**
Haven't been able to find an example where it shows me something. But it should work mathematically speaking...

@harald-lang I don't know if you perhaps know of an example and can check if it works...

### CODE REVIEW

**Comment by harald-lang** [comment]
A good test case would be: Find students that attend all lectures of Russel. -> Result: Carnap

**Comment by mathiasquintero** [comment]
It's not true. Carnap didn't go to Erkentnisstheorie...

**Comment by harald-lang** [comment]
I was wrong.
The above query has an empty results because Carnap does not attend "Erkenntnistheorie". Actually no student attends it. ;)
However, the following works: Find students that attend all lectures of Popper. -> Result: Carnap

**Comment by harald-lang** [comment]
Thanks für your contribution. :)

I also added the ZehnkampfD relation from the latest exercise sheet.

**Comment by mathiasquintero** [comment]
No problem. If you ever need any help, me and my awful coding style are here :)

**Pull request merged**
